lang: en
title: bwForCluster NEMO
tagline: HPC cluster for Neuroscience, Elementary Particle Physics, Microsystems Engineering and Materials Science (NEMO).
email: "enm-support@bwhpc.de"
description: >
  HPC cluster for Neuroscience, Elementary Particle Physics, Microsystems Engineering and Materials Science (NEMO).
author: 2021 HPC Team, University of Freiburg
#baseurl: "/"
url: "https://www.nemo.uni-freiburg.de"
permalink: pretty
favicon: /img/nemo-favicon.png
paginate: 9
paginate_path: "/news/page:num"
livereload: true
markdown: kramdown
highlighter: rouge
footer_menu: footer_menu
hide_share_buttons: true
# theme_color: '#008cba'
# fixed_navbar: top

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - kramdown
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed
  source_dir: _sass

feed:
  categories:
    - events
    - news
    - newsletters
    - social

collections:
  newsletters:
    output: true
    permalink: /:collection/:year/:month/:title/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      hide_hero: true
      show_sidebar: false
  -
    scope:
      path: "news"
      type: "posts"
    values:
      author: "NEMO Team Freiburg"
      layout: post
      hide_hero: true
      show_sidebar: false
  -
    scope:
      path: "newsletters"
      type: "newsletters"
    values:
      author: "NEMO Team Freiburg"
      layout: post
      hide_hero: true
      show_sidebar: false
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      author: "NEMO Team Freiburg"
      layout: post
      hide_hero: false
      hero_image: /img/nemo.jpg
      show_sidebar: true
  -
    scope:
      path: "_newsletters"
      type: "newsletters"
    values:
      author: "NEMO Team Freiburg"
      layout: post
      hide_hero: false
      hero_image: /img/node_small.jpg
      image: /img/node_small.jpg
      show_sidebar: true
  -
    scope:
      path: "nemo"
      type: "pages"
    values:
      layout: page
      hide_hero: true
      show_sidebar: false
      menubar: nemo-menu
  -
    scope:
      path: "bwhpc"
      type: "pages"
    values:
      layout: page
      hide_hero: true
      show_sidebar: false
      menubar: bwhpc-menu
  -
    scope:
      path: "bwunicluster"
      type: "pages"
    values:
      layout: page
      hide_hero: true
      show_sidebar: false
      menubar: bwuni-menu
  -
    scope:
      path: "support"
      type: "pages"
    values:
      layout: page
      hide_hero: true
      show_sidebar: false
      menubar: support-menu
