# Site Settings
title: bwForCluster NEMO
tagline: HPC cluster for Neuroscience, Elementary Particle Physics, Microsystems Engineering and Materials Science (NEMO).
email: "enm-support@bwhpc.de"
description: >
  HPC cluster for Neuroscience, Elementary Particle Physics, Microsystems Engineering and Materials Science (NEMO).
author: 2020 HPC Team, University of Freiburg
#baseurl: "/"
url: "https://nemo-cluster.github.io"
permalink: pretty
favicon: /favicon.ico
paginate: 9
paginate_path: "/news/page:num"
livereload: true
markdown: kramdown
highlighter: rouge
footer_menu: footer_menu
hide_share_buttons: true
# theme_color: '#008cba'

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - kramdown
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  style: compressed
  source_dir: _sass


feed:
  categories:
    - social

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      hide_hero: true
      show_sidebar: false
  -
    scope:
      path: "documentation"
    values:
      layout: page
      hide_hero: true
      show_sidebar: false
      toc: true
      menubar: doc-menu
  -
    scope:
      path: "nemo-documentation"
    values:
      layout: page
      hide_hero: true
      show_sidebar: false
      toc: true
      menubar: doc-menu
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "NEMO Team"
      layout: post
      hide_hero: true
      show_sidebar: true

